### ISSUE TITLE
TypeError: Cannot read property '_identifier' of undefined

### ISSUE THREAD

**Issue by Dean151** [Dean151/Aln-NodeJs#10]
```
TypeError: Cannot read property '_identifier' of undefined
    at FeederCoordinator.getFeeder (/var/www/alnpet/src/feeder-coordinator.js:140:24)
    at Server.router.route.post (/var/www/alnpet/src/server.js:63:37)
    at Layer.handle [as handle_request] (/var/www/alnpet/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/alnpet/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/www/alnpet/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/alnpet/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/alnpet/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/var/www/alnpet/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/alnpet/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/var/www/alnpet/node_modules/express/lib/router/layer.js:91:12)
```

**Comment by Dean151** [comment]
039af42fde33d868e91c8193111fea5f0d9d3110
