### ISSUE TITLE
ER_DUP_ENTRY: Duplicate entry

### ISSUE THREAD

**Issue by Dean151** [Dean151/Aln-NodeJs#9]
```
Error: ER_DUP_ENTRY: Duplicate entry '........' for key 'identifier'
    at Query.Sequence._packetToError (/var/www/alnpet/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/var/www/alnpet/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/var/www/alnpet/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/var/www/alnpet/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/var/www/alnpet/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/var/www/alnpet/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/var/www/alnpet/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    --------------------
    at Protocol._enqueue (/var/www/alnpet/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/var/www/alnpet/node_modules/mysql/lib/Connection.js:200:25)
    at Query.con.query (/var/www/alnpet/src/database-coordinator.js:67:16)
    at Query.<anonymous> (/var/www/alnpet/node_modules/mysql/lib/Connection.js:502:10)
    at Query._callback (/var/www/alnpet/node_modules/mysql/lib/Connection.js:468:16)
    at Query.Sequence.end (/var/www/alnpet/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query._handleFinalResultPacket (/var/www/alnpet/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.OkPacket (/var/www/alnpet/node_modules/mysql/lib/protocol/sequences/Query.js:72:10)
    at Protocol._parsePacket (/var/www/alnpet/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/var/www/alnpet/node_modules/mysql/lib/protocol/Parser.js:76:12)
```

**Comment by Dean151** [comment]
60ba45493941da6e8f1a300bf0541e910fe4ffb5
